support Global exception for NotFound and Operational Sqlalchemy Error
tracim/tracim_backend pull request #77
Opened 2018-05-17 14:49 UTC by inkhey

need https://github.com/algoo/hapic/pull/49 (probably in hapic 0.40)
closes #59 

Add support for NotFound and Operational Error (Sqlalchemy) Exception by hapic for all requests.
Those error as not as clear as it should be, we need to fix this later, see #76

2018-06-01 10:25 UTC, buxx requested changes

2018-06-01 10:25 UTC, buxx commented on tracim/__init__.py
> +        default_error_builder=ErrorSchema()
@inkhey Can you activate debug mode if tracim is run in debug mode ?

2018-06-01 12:28 UTC, lebouquetin requested changes

2018-06-01 12:28 UTC, lebouquetin commented on tracim/__init__.py
> +        default_error_builder=ErrorSchema()
+1

2018-06-04 07:39 UTC, inkhey commented on tracim/__init__.py
> +        default_error_builder=ErrorSchema()
Done.

2018-06-04 10:49 UTC, merged