WIP:Fix/better content types and status code
tracim/tracim_backend pull request #93
Opened 2018-06-28 14:58 UTC by inkhey

need #91

2018-07-06 11:38 UTC, lebouquetin commented on tracim/lib/core/content.py
> +            raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc  # nopep8
with this implementation, we will never know if the `ContentNotFound` comes from `parent` not found or from content not existing

2018-07-06 11:38 UTC, lebouquetin commented on tracim/lib/core/content.py
> +        if not new_label:
You dont know here if the label is mandatory. For example, for modifying a comment, this method was working before your commits. Now it's not possible anymore.

2018-07-06 12:54 UTC, inkhey commented on tracim/lib/core/content.py
> +        if not new_label:
- Label is mandatory for all content but comment, accepting it or make this test in at a higher level look like a bad idea.
- This method is actually unneeded for comment as we just need to set status and create comments.
- There is always a specific method to create comments which is distinct from create_content, having a specific method to update_comment make sense.

2018-07-06 13:06 UTC, inkhey commented on tracim/lib/core/content.py
> +            raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc  # nopep8
Not sure to understand.
There is a already a very large range  of reason to have ContentNotFound 
- if content_type, workspace or parent filter are not correct
- content doesn't exist
- user have not right to read this workspace.

2018-07-14 01:30 UTC, lebouquetin requested changes

2018-07-14 01:30 UTC, lebouquetin commented on tracim/lib/core/content.py
> +        elif filename:
this code is buggy : if I set a filename, it is never stored.

2018-07-14 01:30 UTC, lebouquetin commented on tracim/lib/core/content.py
> +            raise EmptyRawContentNotAllowed()
`EmptyRawContentNotAllowed` does not explain that an empty comment has no meaning. The exception should be renamed to something like `EmptyCommentNotAllowed` (by the way, a RawContent with empty content is allowed : when creating a html-document, first revision is empty)

2018-07-14 01:30 UTC, lebouquetin commented on tracim/lib/core/content.py
> +        if parent and not workspace:
parent cant be None because of the assert. So this test is only : `if not workspace`

2018-07-14 01:30 UTC, lebouquetin commented on tracim/lib/core/content.py
> +            raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc  # nopep8
ok. Add a TODO for future refactoring (include explainations about all error cases you identified resulting in a ContentNotFound exception)

2018-07-14 01:30 UTC, lebouquetin commented on tracim/lib/core/content.py
> +        if not new_label:
- Label is mandatory for all content but comment, accepting empty label or make this test at a higher level look like a bad idea.

Comment is a Content, so generic content API  MUST be usable with comments. So, at least your test should be `if not new_label and item.type!=Comment:`.

- This method is actually unneeded for comment as we just need to set status and create comments.

This is currently the case. A common pattern : "Ouvert à l'extension, fermé à la modification". Deciding to use this for Comments for any reason we do not know yet in the future should be possible.

- There is always a specific method to create comments which is distinct from create_content, having a specific method to update_comment make sense. `create_comment()` is a shortcut for creating a content with given description, etc. Addind a `update_comment()` makes sense, but having a low-level API that does not fit Comments is a bad idea.

2018-07-16 07:31 UTC, inkhey commented on tracim/lib/core/content.py
> +        elif filename:
In fact, it doesn't make sense to set both filename and label, a "label_is_a_filename" boolean params instead of filename seems like a good option.

2018-07-16 08:57 UTC, inkhey commented on tracim/lib/core/content.py
> +        if not new_label:
Done.

2018-07-16 08:57 UTC, inkhey commented on tracim/lib/core/content.py
> +            raise EmptyRawContentNotAllowed()
Done.

2018-07-16 09:53 UTC, inkhey commented on tracim/lib/core/content.py
> +        elif filename:
revert to label or filename strategy with assert to disallow setting both.

2018-07-16 10:01 UTC, inkhey commented on tracim/lib/core/content.py
> +            raise ContentNotFound('Content "{}" not found in database'.format(content_id)) from exc  # nopep8
Done

2018-07-18 11:27 UTC, merged